//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CC_device_emulator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CC_device_emulator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to areuglhrltrk6ff1l9ql.
        /// </summary>
        internal static string ClientBathroomId {
            get {
                return ResourceManager.GetString("ClientBathroomId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bathroomPassw0)rd9.
        /// </summary>
        internal static string ClientBathroomPassword {
            get {
                return ResourceManager.GetString("ClientBathroomPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to are7qiad2ts4k7934fkk.
        /// </summary>
        internal static string ClientKitchenId {
            get {
                return ResourceManager.GetString("ClientKitchenId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to devicePassw0)rd9.
        /// </summary>
        internal static string ClientKitchenPassword {
            get {
                return ResourceManager.GetString("ClientKitchenPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bathroom.
        /// </summary>
        internal static string TopicBathroom {
            get {
                return ResourceManager.GetString("TopicBathroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kitchen.
        /// </summary>
        internal static string TopicKitchen {
            get {
                return ResourceManager.GetString("TopicKitchen", resourceCulture);
            }
        }
    }
}
